openapi: 3.0.3
info:
  title: Health Declaration Information
  description: Health Declaration Information Specification
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /health-declaration-information:
    post:
      tags:
        - createInformation
      summary: create the health declaration information
      operationId: createInformation
      requestBody:
        description: Create the health declaration information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthDeclarationInformationModel'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectSuccessResponse'
    get:
      tags:
        - getListHealthDeclarationInformation
      summary: Get list health declaration information
      operationId: getListHealthDeclarationInformation
      parameters:
        - in: query
          name: page
          description: page number, start at page 0, each page will return 20 items
          schema:
            type: integer
            minimum: 0
            default: 0
          required: true
      responses:
        '200':
          description: Get list health declaration information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListHealthDeclarationInformation'
  /health-declaration-information/{id}:
    get:
      tags:
        - getHealthDeclarationInformationById
      summary: Get user health declaration information by id
      operationId: getHealthDeclarationInformationByID
      parameters:
        - name: id
          in: path
          description: Health Declaration Information Id
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: Get health declaration information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthDeclarationInformationModel'
    delete:
      tags:
        - deleteHealthDeclarationInformationById
      summary: Delete user health declaration information by id
      operationId: deleteHealthDeclarationInformationById
      parameters:
        - name: id
          in: path
          description: Health Declaration Information Id
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: Delete user health declaration information by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectSuccessResponse'

components:
  schemas:
    ListHealthDeclarationInformation:
      type: object
      properties:
        currentPage:
          type: integer
        totalPage:
          type: integer
        totalElements:
          type: integer
        healthDeclarationInformations:
          type: array
          items:
            $ref: '#/components/schemas/HealthDeclarationInformationModel'
    HealthDeclarationInformationModel:
      type: object
      required:
        - fullName
        - idCardNumber
        - birthYear
        - gender
        - nationality
        - address
        - phone
        - personalQuestionsLast14Days
      properties:
        id:
          type: string
        isRegisterForOther:
          type: boolean
          default: false
        fullName:
          type: string
          description: only allow words and spaces
          pattern: '^\w+( +\w+)*$'
          minLength: 1
          maxLength: 100
        idCardNumber:
          type: string
          pattern: '^\d{1,}'
          maxLength: 25
        birthYear:
          type: string
          pattern: '^(1(8|9)\d{2}|2\d{3})'
        gender:
          $ref: '#/components/schemas/Gender'
        nationality:
          $ref: '#/components/schemas/Nationality'
        address:
          $ref: '#/components/schemas/Address'
        phone:
          type: string
          description: support from 9 numbers to 14 numbers
          pattern: '^\d{9,14}$'
        email:
          type: string
          pattern: '\S+@\S+\.\S+'
        personalQuestionsLast14Days:
          $ref: '#/components/schemas/PersonalQuestionsLast14Days'
    Gender:
      type: string
      enum:
        - MALE
        - FEMALE
        - OTHER
    Nationality:
      type: string
      enum:
        - VIETNAMESE
        - AMERICAN
        - ALBANIAN
    Address:
      type: object
      required:
        - province
        - district
        - ward
        - street
      properties:
        province:
          type: string
          pattern: '^\w+( +\w+)*$'
          minLength: 1
          maxLength: 70
        district:
          type: string
          pattern: '^\w+( +\w+)*$'
          minLength: 1
          maxLength: 70
        ward:
          type: string
          pattern: '^\w+( +\w+)*$'
          minLength: 1
          maxLength: 70
        street:
          type: string
          pattern: '^\w+( +\w+)*$'
          minLength: 1
          maxLength: 100
    PersonalQuestionsLast14Days:
      type: object
      properties:
        isTraveling:
          type: boolean
          default: false
        isContactWithInfectedCovid19Person:
          type: boolean
          default: false
        haveCovid19Manifestations:
          type: boolean
          default: false

    ObjectSuccessResponse:
      type: object
      properties:
        id:
          type: string
        responseCode:
          type: integer
          format: int32
        message:
          type: string
        timestamp:
          type: string

